# Generated by Django 4.0.4 on 2022-11-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=40)),
                ('mobile_number', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('leaves', models.IntegerField()),
            ],
        ),
    ]
